// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//
//      This file was generated from this data file:
//      E:\RL_CardGame_Build\Assets/GameDataEditor/Resources/gde_data.txt
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.Video;
using System;
using System.Collections.Generic;

using GameDataEditor;

namespace GameDataEditor
{
    public class GDEASkillData : IGDEData
    {
        static string LvKey = "Lv";
		int _Lv;
        public int Lv
        {
            get { return _Lv; }
            set {
                if (_Lv != value)
                {
                    _Lv = value;
					GDEDataManager.SetInt(_key, LvKey, _Lv);
                }
            }
        }

        static string IdKey = "Id";
		int _Id;
        public int Id
        {
            get { return _Id; }
            set {
                if (_Id != value)
                {
                    _Id = value;
					GDEDataManager.SetInt(_key, IdKey, _Id);
                }
            }
        }

        public GDEASkillData(string key) : base(key)
        {
            GDEDataManager.RegisterItem(this.SchemaName(), key);
        }
        public override Dictionary<string, object> SaveToDict()
		{
			var dict = new Dictionary<string, object>();
			dict.Add(GDMConstants.SchemaKey, "ASkill");
			
            dict.Merge(true, Lv.ToGDEDict(LvKey));
            dict.Merge(true, Id.ToGDEDict(IdKey));
            return dict;
		}

        public override void UpdateCustomItems(bool rebuildKeyList)
        {
        }

        public override void LoadFromDict(string dataKey, Dictionary<string, object> dict)
        {
            _key = dataKey;

			if (dict == null)
				LoadFromSavedData(dataKey);
			else
			{
                dict.TryGetInt(LvKey, out _Lv);
                dict.TryGetInt(IdKey, out _Id);
                LoadFromSavedData(dataKey);
			}
		}

        public override void LoadFromSavedData(string dataKey)
		{
			_key = dataKey;
			
            _Lv = GDEDataManager.GetInt(_key, LvKey, _Lv);
            _Id = GDEDataManager.GetInt(_key, IdKey, _Id);
        }

        public GDEASkillData ShallowClone()
		{
			string newKey = Guid.NewGuid().ToString();
			GDEASkillData newClone = new GDEASkillData(newKey);

            newClone.Lv = Lv;
            newClone.Id = Id;

            return newClone;
		}

        public GDEASkillData DeepClone()
		{
			GDEASkillData newClone = ShallowClone();
            return newClone;
		}

        public void Reset_Lv()
        {
            GDEDataManager.ResetToDefault(_key, LvKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(LvKey, out _Lv);
        }

        public void Reset_Id()
        {
            GDEDataManager.ResetToDefault(_key, IdKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(IdKey, out _Id);
        }

        public void ResetAll()
        {
             #if !UNITY_WEBPLAYER
             GDEDataManager.DeregisterItem(this.SchemaName(), _key);
             #else

            GDEDataManager.ResetToDefault(_key, LvKey);
            GDEDataManager.ResetToDefault(_key, IdKey);


            #endif

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            LoadFromDict(_key, dict);
        }
    }
}
