// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//
//      This file was generated from this data file:
//      E:\RL_CardGame_Build\Assets/GameDataEditor/Resources/gde_data.txt
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.Video;
using System;
using System.Collections.Generic;

using GameDataEditor;

namespace GameDataEditor
{
    public class GDEEquipmentData : IGDEData
    {
        static string lockedKey = "locked";
		bool _locked;
        public bool locked
        {
            get { return _locked; }
            set {
                if (_locked != value)
                {
                    _locked = value;
					GDEDataManager.SetBool(_key, lockedKey, _locked);
                }
            }
        }

        static string equipIdKey = "equipId";
		int _equipId;
        public int equipId
        {
            get { return _equipId; }
            set {
                if (_equipId != value)
                {
                    _equipId = value;
					GDEDataManager.SetInt(_key, equipIdKey, _equipId);
                }
            }
        }

        static string equipLvKey = "equipLv";
		int _equipLv;
        public int equipLv
        {
            get { return _equipLv; }
            set {
                if (_equipLv != value)
                {
                    _equipLv = value;
					GDEDataManager.SetInt(_key, equipLvKey, _equipLv);
                }
            }
        }

        static string equipTypeKey = "equipType";
		int _equipType;
        public int equipType
        {
            get { return _equipType; }
            set {
                if (_equipType != value)
                {
                    _equipType = value;
					GDEDataManager.SetInt(_key, equipTypeKey, _equipType);
                }
            }
        }

        static string equipBattleForceKey = "equipBattleForce";
		int _equipBattleForce;
        public int equipBattleForce
        {
            get { return _equipBattleForce; }
            set {
                if (_equipBattleForce != value)
                {
                    _equipBattleForce = value;
					GDEDataManager.SetInt(_key, equipBattleForceKey, _equipBattleForce);
                }
            }
        }

        static string indexKey = "index";
		int _index;
        public int index
        {
            get { return _index; }
            set {
                if (_index != value)
                {
                    _index = value;
					GDEDataManager.SetInt(_key, indexKey, _index);
                }
            }
        }

        static string numKey = "num";
		int _num;
        public int num
        {
            get { return _num; }
            set {
                if (_num != value)
                {
                    _num = value;
					GDEDataManager.SetInt(_key, numKey, _num);
                }
            }
        }

        static string upLvKey = "upLv";
		int _upLv;
        public int upLv
        {
            get { return _upLv; }
            set {
                if (_upLv != value)
                {
                    _upLv = value;
					GDEDataManager.SetInt(_key, upLvKey, _upLv);
                }
            }
        }

        static string hashcodeKey = "hashcode";
		int _hashcode;
        public int hashcode
        {
            get { return _hashcode; }
            set {
                if (_hashcode != value)
                {
                    _hashcode = value;
					GDEDataManager.SetInt(_key, hashcodeKey, _hashcode);
                }
            }
        }

        static string OwnerHashcodeKey = "OwnerHashcode";
		int _OwnerHashcode;
        public int OwnerHashcode
        {
            get { return _OwnerHashcode; }
            set {
                if (_OwnerHashcode != value)
                {
                    _OwnerHashcode = value;
					GDEDataManager.SetInt(_key, OwnerHashcodeKey, _OwnerHashcode);
                }
            }
        }

        public GDEEquipmentData(string key) : base(key)
        {
            GDEDataManager.RegisterItem(this.SchemaName(), key);
        }
        public override Dictionary<string, object> SaveToDict()
		{
			var dict = new Dictionary<string, object>();
			dict.Add(GDMConstants.SchemaKey, "Equipment");
			
            dict.Merge(true, locked.ToGDEDict(lockedKey));
            dict.Merge(true, equipId.ToGDEDict(equipIdKey));
            dict.Merge(true, equipLv.ToGDEDict(equipLvKey));
            dict.Merge(true, equipType.ToGDEDict(equipTypeKey));
            dict.Merge(true, equipBattleForce.ToGDEDict(equipBattleForceKey));
            dict.Merge(true, index.ToGDEDict(indexKey));
            dict.Merge(true, num.ToGDEDict(numKey));
            dict.Merge(true, upLv.ToGDEDict(upLvKey));
            dict.Merge(true, hashcode.ToGDEDict(hashcodeKey));
            dict.Merge(true, OwnerHashcode.ToGDEDict(OwnerHashcodeKey));
            return dict;
		}

        public override void UpdateCustomItems(bool rebuildKeyList)
        {
        }

        public override void LoadFromDict(string dataKey, Dictionary<string, object> dict)
        {
            _key = dataKey;

			if (dict == null)
				LoadFromSavedData(dataKey);
			else
			{
                dict.TryGetBool(lockedKey, out _locked);
                dict.TryGetInt(equipIdKey, out _equipId);
                dict.TryGetInt(equipLvKey, out _equipLv);
                dict.TryGetInt(equipTypeKey, out _equipType);
                dict.TryGetInt(equipBattleForceKey, out _equipBattleForce);
                dict.TryGetInt(indexKey, out _index);
                dict.TryGetInt(numKey, out _num);
                dict.TryGetInt(upLvKey, out _upLv);
                dict.TryGetInt(hashcodeKey, out _hashcode);
                dict.TryGetInt(OwnerHashcodeKey, out _OwnerHashcode);
                LoadFromSavedData(dataKey);
			}
		}

        public override void LoadFromSavedData(string dataKey)
		{
			_key = dataKey;
			
            _locked = GDEDataManager.GetBool(_key, lockedKey, _locked);
            _equipId = GDEDataManager.GetInt(_key, equipIdKey, _equipId);
            _equipLv = GDEDataManager.GetInt(_key, equipLvKey, _equipLv);
            _equipType = GDEDataManager.GetInt(_key, equipTypeKey, _equipType);
            _equipBattleForce = GDEDataManager.GetInt(_key, equipBattleForceKey, _equipBattleForce);
            _index = GDEDataManager.GetInt(_key, indexKey, _index);
            _num = GDEDataManager.GetInt(_key, numKey, _num);
            _upLv = GDEDataManager.GetInt(_key, upLvKey, _upLv);
            _hashcode = GDEDataManager.GetInt(_key, hashcodeKey, _hashcode);
            _OwnerHashcode = GDEDataManager.GetInt(_key, OwnerHashcodeKey, _OwnerHashcode);
        }

        public GDEEquipmentData ShallowClone()
		{
			string newKey = Guid.NewGuid().ToString();
			GDEEquipmentData newClone = new GDEEquipmentData(newKey);

            newClone.locked = locked;
            newClone.equipId = equipId;
            newClone.equipLv = equipLv;
            newClone.equipType = equipType;
            newClone.equipBattleForce = equipBattleForce;
            newClone.index = index;
            newClone.num = num;
            newClone.upLv = upLv;
            newClone.hashcode = hashcode;
            newClone.OwnerHashcode = OwnerHashcode;

            return newClone;
		}

        public GDEEquipmentData DeepClone()
		{
			GDEEquipmentData newClone = ShallowClone();
            return newClone;
		}

        public void Reset_locked()
        {
            GDEDataManager.ResetToDefault(_key, lockedKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetBool(lockedKey, out _locked);
        }

        public void Reset_equipId()
        {
            GDEDataManager.ResetToDefault(_key, equipIdKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(equipIdKey, out _equipId);
        }

        public void Reset_equipLv()
        {
            GDEDataManager.ResetToDefault(_key, equipLvKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(equipLvKey, out _equipLv);
        }

        public void Reset_equipType()
        {
            GDEDataManager.ResetToDefault(_key, equipTypeKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(equipTypeKey, out _equipType);
        }

        public void Reset_equipBattleForce()
        {
            GDEDataManager.ResetToDefault(_key, equipBattleForceKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(equipBattleForceKey, out _equipBattleForce);
        }

        public void Reset_index()
        {
            GDEDataManager.ResetToDefault(_key, indexKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(indexKey, out _index);
        }

        public void Reset_num()
        {
            GDEDataManager.ResetToDefault(_key, numKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(numKey, out _num);
        }

        public void Reset_upLv()
        {
            GDEDataManager.ResetToDefault(_key, upLvKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(upLvKey, out _upLv);
        }

        public void Reset_hashcode()
        {
            GDEDataManager.ResetToDefault(_key, hashcodeKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(hashcodeKey, out _hashcode);
        }

        public void Reset_OwnerHashcode()
        {
            GDEDataManager.ResetToDefault(_key, OwnerHashcodeKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(OwnerHashcodeKey, out _OwnerHashcode);
        }

        public void ResetAll()
        {
             #if !UNITY_WEBPLAYER
             GDEDataManager.DeregisterItem(this.SchemaName(), _key);
             #else

            GDEDataManager.ResetToDefault(_key, equipIdKey);
            GDEDataManager.ResetToDefault(_key, equipLvKey);
            GDEDataManager.ResetToDefault(_key, equipTypeKey);
            GDEDataManager.ResetToDefault(_key, equipBattleForceKey);
            GDEDataManager.ResetToDefault(_key, indexKey);
            GDEDataManager.ResetToDefault(_key, numKey);
            GDEDataManager.ResetToDefault(_key, upLvKey);
            GDEDataManager.ResetToDefault(_key, hashcodeKey);
            GDEDataManager.ResetToDefault(_key, OwnerHashcodeKey);
            GDEDataManager.ResetToDefault(_key, lockedKey);


            #endif

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            LoadFromDict(_key, dict);
        }
    }
}
