// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//
//      This file was generated from this data file:
//      E:\RL_CardGame_Build\Assets/GameDataEditor/Resources/gde_data.txt
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.Video;
using System;
using System.Collections.Generic;

using GameDataEditor;

namespace GameDataEditor
{
    public class GDEgoddesData : IGDEData
    {
        static string idKey = "id";
		int _id;
        public int id
        {
            get { return _id; }
            set {
                if (_id != value)
                {
                    _id = value;
					GDEDataManager.SetInt(_key, idKey, _id);
                }
            }
        }

        static string lvKey = "lv";
		int _lv;
        public int lv
        {
            get { return _lv; }
            set {
                if (_lv != value)
                {
                    _lv = value;
					GDEDataManager.SetInt(_key, lvKey, _lv);
                }
            }
        }

        static string starKey = "star";
		int _star;
        public int star
        {
            get { return _star; }
            set {
                if (_star != value)
                {
                    _star = value;
					GDEDataManager.SetInt(_key, starKey, _star);
                }
            }
        }

        static string UseTeamIdKey = "UseTeamId";
		public List<int>      UseTeamId;
		public void Set_UseTeamId()
        {
	        GDEDataManager.SetIntList(_key, UseTeamIdKey, UseTeamId);
		}
		

        public GDEgoddesData(string key) : base(key)
        {
            GDEDataManager.RegisterItem(this.SchemaName(), key);
        }
        public override Dictionary<string, object> SaveToDict()
		{
			var dict = new Dictionary<string, object>();
			dict.Add(GDMConstants.SchemaKey, "goddes");
			
            dict.Merge(true, id.ToGDEDict(idKey));
            dict.Merge(true, lv.ToGDEDict(lvKey));
            dict.Merge(true, star.ToGDEDict(starKey));

            dict.Merge(true, UseTeamId.ToGDEDict(UseTeamIdKey));
            return dict;
		}

        public override void UpdateCustomItems(bool rebuildKeyList)
        {
        }

        public override void LoadFromDict(string dataKey, Dictionary<string, object> dict)
        {
            _key = dataKey;

			if (dict == null)
				LoadFromSavedData(dataKey);
			else
			{
                dict.TryGetInt(idKey, out _id);
                dict.TryGetInt(lvKey, out _lv);
                dict.TryGetInt(starKey, out _star);

                dict.TryGetIntList(UseTeamIdKey, out UseTeamId);
                LoadFromSavedData(dataKey);
			}
		}

        public override void LoadFromSavedData(string dataKey)
		{
			_key = dataKey;
			
            _id = GDEDataManager.GetInt(_key, idKey, _id);
            _lv = GDEDataManager.GetInt(_key, lvKey, _lv);
            _star = GDEDataManager.GetInt(_key, starKey, _star);

            UseTeamId = GDEDataManager.GetIntList(_key, UseTeamIdKey, UseTeamId);
        }

        public GDEgoddesData ShallowClone()
		{
			string newKey = Guid.NewGuid().ToString();
			GDEgoddesData newClone = new GDEgoddesData(newKey);

            newClone.id = id;
            newClone.lv = lv;
            newClone.star = star;

            newClone.UseTeamId = new List<int>(UseTeamId);
			newClone.Set_UseTeamId();

            return newClone;
		}

        public GDEgoddesData DeepClone()
		{
			GDEgoddesData newClone = ShallowClone();
            return newClone;
		}

        public void Reset_id()
        {
            GDEDataManager.ResetToDefault(_key, idKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(idKey, out _id);
        }

        public void Reset_lv()
        {
            GDEDataManager.ResetToDefault(_key, lvKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(lvKey, out _lv);
        }

        public void Reset_star()
        {
            GDEDataManager.ResetToDefault(_key, starKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(starKey, out _star);
        }

        public void Reset_UseTeamId()
        {
	        GDEDataManager.ResetToDefault(_key, UseTeamIdKey);

	        Dictionary<string, object> dict;
	        GDEDataManager.Get(_key, out dict);
	        dict.TryGetIntList(UseTeamIdKey, out UseTeamId);
        }
		

        public void ResetAll()
        {
             #if !UNITY_WEBPLAYER
             GDEDataManager.DeregisterItem(this.SchemaName(), _key);
             #else

            GDEDataManager.ResetToDefault(_key, idKey);
            GDEDataManager.ResetToDefault(_key, lvKey);
            GDEDataManager.ResetToDefault(_key, starKey);
            GDEDataManager.ResetToDefault(_key, UseTeamIdKey);


            #endif

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            LoadFromDict(_key, dict);
        }
    }
}
