// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//
//      This file was generated from this data file:
//      E:\RL_CardGame_Build\Assets/GameDataEditor/Resources/gde_data.txt
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace GameDataEditor
{
    public partial class GDEItemKeys
    {
        public static string Player_CurrentPlayer = "CurrentPlayer";
        public static string Setting_Setting = "Setting";
        public static string Equipment_EquipEmpty = "EquipEmpty";
        public static string Hero_BasicHero = "BasicHero";
        public static string RoleAttritube_BasicRA = "BasicRA";
        public static string RoleAttritube_BasicEnemyRA = "BasicEnemyRA";
        public static string Item_MaterialEmpty = "MaterialEmpty";
        public static string ResidentMovement_EmptyResidentMovement = "EmptyResidentMovement";
        public static string unitTeam_emptyHeroTeam = "emptyHeroTeam";
        public static string ASkill_normalAttack = "normalAttack";
        public static string goddess_baseGoddess = "baseGoddess";
        public static string timeTask_emptyTimeTask = "emptyTimeTask";
        public static string townBuilding_newTownBuilding = "newTownBuilding";
        public static string Achievement_newAchievement = "newAchievement";
        public static string Anim_EmptyAnim = "EmptyAnim";
        public static string NPC_noone = "noone";
        public static string Rune_RuneEmpty = "RuneEmpty";
        public static string goddessAtti_emptyGAtti = "emptyGAtti";
        public static string HeroAltarPool_emptyPool = "emptyPool";
        public static string Section_nullSection = "nullSection";
    }
}
