// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//
//      This file was generated from this data file:
//      E:\RL_CardGame_Build\Assets/GameDataEditor/Resources/gde_data.txt
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.Video;
using System;
using System.Collections.Generic;

using GameDataEditor;

namespace GameDataEditor
{
    public class GDEItemData : IGDEData
    {
        static string numKey = "num";
		int _num;
        public int num
        {
            get { return _num; }
            set {
                if (_num != value)
                {
                    _num = value;
					GDEDataManager.SetInt(_key, numKey, _num);
                }
            }
        }

        static string indexKey = "index";
		int _index;
        public int index
        {
            get { return _index; }
            set {
                if (_index != value)
                {
                    _index = value;
					GDEDataManager.SetInt(_key, indexKey, _index);
                }
            }
        }

        static string idKey = "id";
		string _id;
        public string id
        {
            get { return _id; }
            set {
                if (_id != value)
                {
                    _id = value;
					GDEDataManager.SetString(_key, idKey, _id);
                }
            }
        }

        public GDEItemData(string key) : base(key)
        {
            GDEDataManager.RegisterItem(this.SchemaName(), key);
        }
        public override Dictionary<string, object> SaveToDict()
		{
			var dict = new Dictionary<string, object>();
			dict.Add(GDMConstants.SchemaKey, "Item");
			
            dict.Merge(true, num.ToGDEDict(numKey));
            dict.Merge(true, index.ToGDEDict(indexKey));
            dict.Merge(true, id.ToGDEDict(idKey));
            return dict;
		}

        public override void UpdateCustomItems(bool rebuildKeyList)
        {
        }

        public override void LoadFromDict(string dataKey, Dictionary<string, object> dict)
        {
            _key = dataKey;

			if (dict == null)
				LoadFromSavedData(dataKey);
			else
			{
                dict.TryGetInt(numKey, out _num);
                dict.TryGetInt(indexKey, out _index);
                dict.TryGetString(idKey, out _id);
                LoadFromSavedData(dataKey);
			}
		}

        public override void LoadFromSavedData(string dataKey)
		{
			_key = dataKey;
			
            _num = GDEDataManager.GetInt(_key, numKey, _num);
            _index = GDEDataManager.GetInt(_key, indexKey, _index);
            _id = GDEDataManager.GetString(_key, idKey, _id);
        }

        public GDEItemData ShallowClone()
		{
			string newKey = Guid.NewGuid().ToString();
			GDEItemData newClone = new GDEItemData(newKey);

            newClone.num = num;
            newClone.index = index;
            newClone.id = id;

            return newClone;
		}

        public GDEItemData DeepClone()
		{
			GDEItemData newClone = ShallowClone();
            return newClone;
		}

        public void Reset_num()
        {
            GDEDataManager.ResetToDefault(_key, numKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(numKey, out _num);
        }

        public void Reset_index()
        {
            GDEDataManager.ResetToDefault(_key, indexKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(indexKey, out _index);
        }

        public void Reset_id()
        {
            GDEDataManager.ResetToDefault(_key, idKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetString(idKey, out _id);
        }

        public void ResetAll()
        {
             #if !UNITY_WEBPLAYER
             GDEDataManager.DeregisterItem(this.SchemaName(), _key);
             #else

            GDEDataManager.ResetToDefault(_key, idKey);
            GDEDataManager.ResetToDefault(_key, numKey);
            GDEDataManager.ResetToDefault(_key, indexKey);


            #endif

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            LoadFromDict(_key, dict);
        }
    }
}
