// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//
//      This file was generated from this data file:
//      E:\RL_CardGame_Build\Assets/GameDataEditor/Resources/gde_data.txt
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.Video;
using System;
using System.Collections.Generic;

using GameDataEditor;

namespace GameDataEditor
{
    public class GDEResidentMovementData : IGDEData
    {
        static string CurrentDayNightIdKey = "CurrentDayNightId";
		int _CurrentDayNightId;
        public int CurrentDayNightId
        {
            get { return _CurrentDayNightId; }
            set {
                if (_CurrentDayNightId != value)
                {
                    _CurrentDayNightId = value;
					GDEDataManager.SetInt(_key, CurrentDayNightIdKey, _CurrentDayNightId);
                }
            }
        }

        static string CurrentSeasonIdKey = "CurrentSeasonId";
		int _CurrentSeasonId;
        public int CurrentSeasonId
        {
            get { return _CurrentSeasonId; }
            set {
                if (_CurrentSeasonId != value)
                {
                    _CurrentSeasonId = value;
					GDEDataManager.SetInt(_key, CurrentSeasonIdKey, _CurrentSeasonId);
                }
            }
        }

        public GDEResidentMovementData(string key) : base(key)
        {
            GDEDataManager.RegisterItem(this.SchemaName(), key);
        }
        public override Dictionary<string, object> SaveToDict()
		{
			var dict = new Dictionary<string, object>();
			dict.Add(GDMConstants.SchemaKey, "ResidentMovement");
			
            dict.Merge(true, CurrentDayNightId.ToGDEDict(CurrentDayNightIdKey));
            dict.Merge(true, CurrentSeasonId.ToGDEDict(CurrentSeasonIdKey));
            return dict;
		}

        public override void UpdateCustomItems(bool rebuildKeyList)
        {
        }

        public override void LoadFromDict(string dataKey, Dictionary<string, object> dict)
        {
            _key = dataKey;

			if (dict == null)
				LoadFromSavedData(dataKey);
			else
			{
                dict.TryGetInt(CurrentDayNightIdKey, out _CurrentDayNightId);
                dict.TryGetInt(CurrentSeasonIdKey, out _CurrentSeasonId);
                LoadFromSavedData(dataKey);
			}
		}

        public override void LoadFromSavedData(string dataKey)
		{
			_key = dataKey;
			
            _CurrentDayNightId = GDEDataManager.GetInt(_key, CurrentDayNightIdKey, _CurrentDayNightId);
            _CurrentSeasonId = GDEDataManager.GetInt(_key, CurrentSeasonIdKey, _CurrentSeasonId);
        }

        public GDEResidentMovementData ShallowClone()
		{
			string newKey = Guid.NewGuid().ToString();
			GDEResidentMovementData newClone = new GDEResidentMovementData(newKey);

            newClone.CurrentDayNightId = CurrentDayNightId;
            newClone.CurrentSeasonId = CurrentSeasonId;

            return newClone;
		}

        public GDEResidentMovementData DeepClone()
		{
			GDEResidentMovementData newClone = ShallowClone();
            return newClone;
		}

        public void Reset_CurrentDayNightId()
        {
            GDEDataManager.ResetToDefault(_key, CurrentDayNightIdKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(CurrentDayNightIdKey, out _CurrentDayNightId);
        }

        public void Reset_CurrentSeasonId()
        {
            GDEDataManager.ResetToDefault(_key, CurrentSeasonIdKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(CurrentSeasonIdKey, out _CurrentSeasonId);
        }

        public void ResetAll()
        {
             #if !UNITY_WEBPLAYER
             GDEDataManager.DeregisterItem(this.SchemaName(), _key);
             #else

            GDEDataManager.ResetToDefault(_key, CurrentSeasonIdKey);
            GDEDataManager.ResetToDefault(_key, CurrentDayNightIdKey);


            #endif

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            LoadFromDict(_key, dict);
        }
    }
}
