// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//
//      This file was generated from this data file:
//      E:\RL_CardGame_Build\Assets/GameDataEditor/Resources/gde_data.txt
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace GameDataEditor
{
    public partial class GDESchemaKeys
    {
        public static string Player = "Player";
        public static string Setting = "Setting";
        public static string Equipment = "Equipment";
        public static string Hero = "Hero";
        public static string RoleAttritube = "RoleAttritube";
        public static string Item = "Item";
        public static string ResidentMovement = "ResidentMovement";
        public static string unitTeam = "unitTeam";
        public static string ASkill = "ASkill";
        public static string goddess = "goddess";
        public static string timeTask = "timeTask";
        public static string townBuilding = "townBuilding";
        public static string Achievement = "Achievement";
        public static string Anim = "Anim";
        public static string NPC = "NPC";
        public static string Rune = "Rune";
        public static string goddessAtti = "goddessAtti";
        public static string HeroAltarPool = "HeroAltarPool";
        public static string Section = "Section";
    }
}
