// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//
//      This file was generated from this data file:
//      E:\RL_CardGame_Build\Assets/GameDataEditor/Resources/gde_data.txt
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using UnityEngine.Video;
using System;
using System.Collections.Generic;

using GameDataEditor;

namespace GameDataEditor
{
    public class GDEunitTeamData : IGDEData
    {
        static string goddessKey = "goddess";
		int _goddess;
        public int goddess
        {
            get { return _goddess; }
            set {
                if (_goddess != value)
                {
                    _goddess = value;
					GDEDataManager.SetInt(_key, goddessKey, _goddess);
                }
            }
        }

        static string badgeKey = "badge";
		int _badge;
        public int badge
        {
            get { return _badge; }
            set {
                if (_badge != value)
                {
                    _badge = value;
					GDEDataManager.SetInt(_key, badgeKey, _badge);
                }
            }
        }

        static string idKey = "id";
		int _id;
        public int id
        {
            get { return _id; }
            set {
                if (_id != value)
                {
                    _id = value;
					GDEDataManager.SetInt(_key, idKey, _id);
                }
            }
        }

        static string teamNameKey = "teamName";
		string _teamName;
        public string teamName
        {
            get { return _teamName; }
            set {
                if (_teamName != value)
                {
                    _teamName = value;
					GDEDataManager.SetString(_key, teamNameKey, _teamName);
                }
            }
        }

        static string heroesKey = "heroes";
		public List<int>      heroes;
		public void Set_heroes()
        {
	        GDEDataManager.SetIntList(_key, heroesKey, heroes);
		}
		

        public GDEunitTeamData(string key) : base(key)
        {
            GDEDataManager.RegisterItem(this.SchemaName(), key);
        }
        public override Dictionary<string, object> SaveToDict()
		{
			var dict = new Dictionary<string, object>();
			dict.Add(GDMConstants.SchemaKey, "unitTeam");
			
            dict.Merge(true, goddess.ToGDEDict(goddessKey));
            dict.Merge(true, badge.ToGDEDict(badgeKey));
            dict.Merge(true, id.ToGDEDict(idKey));
            dict.Merge(true, teamName.ToGDEDict(teamNameKey));

            dict.Merge(true, heroes.ToGDEDict(heroesKey));
            return dict;
		}

        public override void UpdateCustomItems(bool rebuildKeyList)
        {
        }

        public override void LoadFromDict(string dataKey, Dictionary<string, object> dict)
        {
            _key = dataKey;

			if (dict == null)
				LoadFromSavedData(dataKey);
			else
			{
                dict.TryGetInt(goddessKey, out _goddess);
                dict.TryGetInt(badgeKey, out _badge);
                dict.TryGetInt(idKey, out _id);
                dict.TryGetString(teamNameKey, out _teamName);

                dict.TryGetIntList(heroesKey, out heroes);
                LoadFromSavedData(dataKey);
			}
		}

        public override void LoadFromSavedData(string dataKey)
		{
			_key = dataKey;
			
            _goddess = GDEDataManager.GetInt(_key, goddessKey, _goddess);
            _badge = GDEDataManager.GetInt(_key, badgeKey, _badge);
            _id = GDEDataManager.GetInt(_key, idKey, _id);
            _teamName = GDEDataManager.GetString(_key, teamNameKey, _teamName);

            heroes = GDEDataManager.GetIntList(_key, heroesKey, heroes);
        }

        public GDEunitTeamData ShallowClone()
		{
			string newKey = Guid.NewGuid().ToString();
			GDEunitTeamData newClone = new GDEunitTeamData(newKey);

            newClone.goddess = goddess;
            newClone.badge = badge;
            newClone.id = id;
            newClone.teamName = teamName;

            newClone.heroes = new List<int>(heroes);
			newClone.Set_heroes();

            return newClone;
		}

        public GDEunitTeamData DeepClone()
		{
			GDEunitTeamData newClone = ShallowClone();
            return newClone;
		}

        public void Reset_goddess()
        {
            GDEDataManager.ResetToDefault(_key, goddessKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(goddessKey, out _goddess);
        }

        public void Reset_badge()
        {
            GDEDataManager.ResetToDefault(_key, badgeKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(badgeKey, out _badge);
        }

        public void Reset_id()
        {
            GDEDataManager.ResetToDefault(_key, idKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(idKey, out _id);
        }

        public void Reset_teamName()
        {
            GDEDataManager.ResetToDefault(_key, teamNameKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetString(teamNameKey, out _teamName);
        }

        public void Reset_heroes()
        {
	        GDEDataManager.ResetToDefault(_key, heroesKey);

	        Dictionary<string, object> dict;
	        GDEDataManager.Get(_key, out dict);
	        dict.TryGetIntList(heroesKey, out heroes);
        }
		

        public void ResetAll()
        {
             #if !UNITY_WEBPLAYER
             GDEDataManager.DeregisterItem(this.SchemaName(), _key);
             #else

            GDEDataManager.ResetToDefault(_key, heroesKey);
            GDEDataManager.ResetToDefault(_key, goddessKey);
            GDEDataManager.ResetToDefault(_key, badgeKey);
            GDEDataManager.ResetToDefault(_key, idKey);
            GDEDataManager.ResetToDefault(_key, teamNameKey);


            #endif

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            LoadFromDict(_key, dict);
        }
    }
}
